### ISSUE TITLE
Why not https://github.com/zimmski/go-mutesting ?

### ISSUE THREAD

**Issue by zimmski** [zabawaba99/gomutate#7]
This is maybe an odd question but why didn't you contribute to https://github.com/zimmski/go-mutesting instead of making your own solution? Was something bugging you?

**Comment by zabawaba99** [comment]
The project was more of an experiment after seeing pitest. After pushing the code is when I saw ended up seeing your project. 

The funny thing is, after I looked through your project I saw that there was some similarities as far as the overall design. It seems we both had a similar mindset around how to solve the problem.

**Comment by zabawaba99** [comment]
Going to go ahead and continue work on this project to see where it goes. When I find a stopping point I wouldn't mind doubling back and contributing.
